services:
  - type: web
    name: akihabara-tcg-warehouse
    runtime: node
    plan: free
    region: oregon
    buildCommand: bun install && bun run build
    startCommand: bash start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_EMAIL
        value: admin@akihabara.com
      - key: ADMIN_PASSWORD
        value: Akihabarat1$
